export const errorMessages = {
  INVALID_CREDENTIALS: 'Invalid credentials',
  INVALID_TOKEN: 'Invalid token',
  INVALID_FORM_DATA: 'Invalid form data',
  INVALID_PASSWORD: 'Invalid password',
  PASSWORDS_DONT_MATCH: 'Passwords do not match',
  USER_NOT_FOUND: 'User not found',
  USER_ALREADY_EXISTS: 'User already exists',
  USER_ALREADY_LOGGED_IN: 'User is already logged in',
  SERVER_ERROR: 'Server error occurred, please try again later',
  NULL_RESPONSE: 'Null response',
  TOKENS_NOT_GENERATED: 'Error generating tokens',
  EMAIL_NOT_FOUND: 'Email not found in payload',
  UNAUTHORIZED: 'User is not authorized to perform this action',

  FAILED_TO_GET_USER_BY_IDENTIFIER: 'Error getting user by identifier',
  FAILED_TO_GET_USER_BY_ID: 'Error getting user by id',
  FAILED_TO_CREATE_USER: 'Failed to create user',
  FAILED_TO_UPDATE_USER: 'Error updating user',
  FAILED_TO_DELETE_USER: 'Error deleting user',
  
  POST_NOT_FOUND: 'Post not found',
  POST_ALREADY_EXISTS: 'Post already exists',
  FAILED_TO_GET_ALL_POSTS: 'Error getting all posts',
  FAILED_TO_GET_POST_BY_ID: 'Error getting post by id',
  FAILED_TO_GET_POST_BY_USERNAME: 'Error getting post by username',
  FAILED_TO_CREATE_POST: 'Failed to create post',
  FAILED_TO_UPDATE_POST: 'Error updating post',
  FAILED_TO_DELETE_POST: 'Error deleting post',
};