export const errorMessages = {
  INVALID_CREDENTIALS: 'Invalid credentials',
  INVALID_TOKEN: 'Invalid token',
  USER_NOT_FOUND: 'User not found',
  USER_ALREADY_EXISTS: 'User already exists',
  SERVER_ERROR: 'Server error occurred, please try again later',
  PASSWORDS_DONT_MATCH: 'Passwords do not match',
  NULL_RESPONSE: 'Null response',
  TOKENS_NOT_GENERATED: 'Error generating tokens',
  FAILED_TO_CREATE_USER: 'Failed to create user',
  NOT_FOUND_USER_IDENTIFIER: 'Error getting user by identifier',
  NOT_FOUND_USER_ID: 'Error getting user by id',
  ERROR_DELETING_USER: 'Error deleting user by email or username',
  USER_ALREADY_LOGGED_IN: 'User is already logged in',
  UNAUTHORIZED: 'User is not authorized to perform this action',
};
